import json
import os

# CONFIGURATION LOADER for Tashi Swarm
# This file loads the P2P keys and networking profile generated by setup.sh

# Resolve paths relative to this script's directory
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
CONFIG_FILE = os.path.join(SCRIPT_DIR, "swarm_config.json")

# --- CONFIGURATION ---
# Path to tashi-tools (inside this repo)
TASHI_TOOLS_DIR = os.path.abspath(os.path.join(SCRIPT_DIR, "..", "..", "tashi-tools"))
# ---------------------

def load_config():
    if not os.path.exists(CONFIG_FILE):
        print(f"ERROR: {CONFIG_FILE} not found. Run 'utils/generate_config.py' first!")
        return {}
    with open(CONFIG_FILE, "r") as f:
        return json.load(f)

DRONE_CONFIG = load_config()

def get_peers():
    """Returns a list of public_key@ip:port for all peers in the swarm"""
    return [f"{cfg['public']}@127.0.0.1:{cfg['port']}" for cfg in DRONE_CONFIG.values()]
